In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,32,7]])

In [3]:
myarr

array([[ 3,  6, 32,  7]])

In [4]:
myarr[0,1]

6

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int32')

In [7]:
myarr[0,1] = 45

In [8]:
myarr

array([[ 3, 45, 32,  7]])

**Array creation : Conversion from other python structure**

In [9]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [10]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [11]:
listarray.dtype

dtype('int32')

In [12]:
listarray.shape

(3, 3)

In [13]:
listarray.size

9

**Intrensic numpy array creation object**  

In [14]:
zeros = np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
zeros.dtype

dtype('float64')

In [17]:
zeros.shape

(2, 5)

In [18]:
rng = np.arange(20) #rng = range

In [19]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
lspace = np.linspace(1,5,12)  #linspace = linearspace

In [21]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [22]:
ide = np.identity(5)  #ide = identity , it provides a identity matrix

In [23]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
ide.shape

(5, 5)

In [25]:
arr = np.arange(99)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [27]:
arr = arr.reshape(3,33)

In [28]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [29]:
arr= arr.ravel()

In [30]:
arr.shape

(99,)

In [31]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [33]:
ar = np.array(x)

In [34]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [35]:
ar.sum(axis=0)   #1+4+7=12

array([12,  8,  9])

In [36]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [38]:
ar.T  #Transposes the array row becomes column and vice-versa

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [39]:
ar.flat

In [41]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [42]:
ar.ndim   # dimensions

2

In [43]:
ar.size

9

In [44]:
ar.nbytes

36

In [46]:
one = np.array([1,2,4,3,34])

In [48]:
one.argmax()    #shows index of largest element

4

In [49]:
one.argmin()

0

In [50]:
one.argsort()

array([0, 1, 3, 2, 4], dtype=int64)

In [51]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [52]:
ar.argmax()

6

In [53]:
ar.argmin()

8

In [54]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [55]:
ar2 = np.array([[1,2,1],
                [4,0,6],
                [8,1,0]])

In [58]:
ar2+ar     #numpy allows to perform mathematical calculation on matrices

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [59]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [60]:
ar-ar2

array([[ 0,  0,  2],
       [ 0,  5,  0],
       [-1,  0,  0]])

In [62]:
np.sqrt(ar)     # gives the underroot of elements 

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [63]:
ar.sum()

29

In [64]:
ar.max()

7

In [65]:
ar.min()

0

In [66]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [67]:
np.count_nonzero(ar)

8

In [68]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))